const mobile = document.querySelector<HTMLButtonElement>('.mobile-toggle');
const navigation = document.querySelector<HTMLElement>('#primary-navigation');
mobile?.addEventListener('click',()=>{const open=mobile.getAttribute('aria-expanded')!=='true';mobile.setAttribute('aria-expanded',String(open));mobile.setAttribute('aria-label',open?'Close navigation':'Open navigation');if(navigation)navigation.dataset.open=String(open)});
for(const toggle of document.querySelectorAll<HTMLButtonElement>('.submenu-toggle'))toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));const parent=toggle.closest<HTMLElement>('.nav-item');if(parent)parent.dataset.expanded=String(open)});
for(const item of document.querySelectorAll<HTMLElement>('.nav-item')){item.addEventListener('mouseenter',()=>{if(innerWidth>850)item.dataset.expanded='true'});item.addEventListener('mouseleave',()=>{if(innerWidth>850&&!item.contains(document.activeElement))item.dataset.expanded='false'});item.addEventListener('focusin',()=>{if(innerWidth>850)item.dataset.expanded='true'})}
document.addEventListener('keydown',event=>{if(event.key==='Escape'){mobile?.setAttribute('aria-expanded','false');if(navigation)navigation.dataset.open='false';document.querySelectorAll<HTMLElement>('.nav-item').forEach(item=>{item.dataset.expanded='false';item.querySelector('.submenu-toggle')?.setAttribute('aria-expanded','false')})}});
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
for(const carousel of document.querySelectorAll<HTMLElement>('[data-carousel]')){
 const slides=[...carousel.querySelectorAll<HTMLElement>('[data-slide]')], dots=[...carousel.querySelectorAll<HTMLButtonElement>('[data-dot]')];
 const pause=carousel.querySelector<HTMLButtonElement>('[data-pause]');let index=0,paused=reduced.matches,hover=false,focused=false;
 const setPause=()=>{pause?.setAttribute('aria-pressed',String(paused));pause?.setAttribute('aria-label',`${paused?'Resume':'Pause'} ${carousel.getAttribute('aria-label')} slideshow`);if(pause)pause.textContent=paused?'▶':'Ⅱ'};
 const show=(next:number,announce=false)=>{index=(next+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.hidden=i!==index;for(const video of slide.querySelectorAll('video')){if(i===index&&!reduced.matches)void video.play().catch(()=>{});else video.pause()}});dots.forEach((dot,i)=>dot.setAttribute('aria-pressed',String(i===index)));const status=carousel.querySelector<HTMLElement>('[data-slide-status]');if(announce&&status)status.textContent=`Slide ${index+1} of ${slides.length}`};
 carousel.querySelector('[data-next]')?.addEventListener('click',()=>show(index+1,true));carousel.querySelector('[data-prev]')?.addEventListener('click',()=>show(index-1,true));dots.forEach((dot,i)=>dot.addEventListener('click',()=>show(i,true)));
 pause?.addEventListener('click',()=>{paused=!paused;setPause()});carousel.addEventListener('mouseenter',()=>hover=true);carousel.addEventListener('mouseleave',()=>hover=false);carousel.addEventListener('focusin',()=>focused=true);carousel.addEventListener('focusout',event=>focused=carousel.contains(event.relatedTarget as Node));
 carousel.addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();show(index+1,true)}if(event.key==='ArrowLeft'){event.preventDefault();show(index-1,true)}});
 show(0);setPause();setInterval(()=>{if(!paused&&!hover&&!focused&&!document.hidden&&carousel.dataset.auto==='true')show(index+1)},7000);
}
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-open-dialog]'))button.addEventListener('click',()=>{const dialog=document.getElementById(button.dataset.openDialog||'') as HTMLDialogElement|null;dialog?.showModal()});
for(const dialog of document.querySelectorAll<HTMLDialogElement>('dialog')){dialog.querySelector('[data-close-dialog]')?.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{const rect=dialog.getBoundingClientRect();if(event.target===dialog&&(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom))dialog.close()})}
const updateMotion=()=>{for(const video of document.querySelectorAll('video'))if(reduced.matches){video.pause();video.removeAttribute('autoplay');video.controls=true}};updateMotion();reduced.addEventListener('change',updateMotion);
const pages:Record<string,string>={'518':'news','2358':'professor','2181':'students','1604':'research','761':'project','1534':'resource','1064':'publications','55':'contact','690':'recruitment','1180':'sns'};
const legacy=new URLSearchParams(location.search).get('page_id');if(legacy&&pages[legacy])location.replace(`${import.meta.env.BASE_URL}${pages[legacy]}/`);
