import fs from 'node:fs';import path from 'node:path';import {load} from 'cheerio';import {routes,filesIn,bytesIn} from './validation.mjs';
const preview=process.env.SITE_MODE!=='production',base=preview?'/lab-homepage-preview':'';const origin='https://vision3d-lab.github.io';const projectNames=JSON.parse(fs.readFileSync('docs/existing-projects.json'));let errors=[];const htmlFiles=filesIn('dist').filter(f=>f.endsWith('.html'));const docs=new Map();
for(const file of htmlFiles)docs.set(file,load(fs.readFileSync(file,'utf8')));
for(const route of routes){const file=path.join('dist',route,'index.html');if(!fs.existsSync(file))errors.push(`Missing route ${route}`)}
for(const [file,$] of docs){const route='/'+path.relative('dist',file).replace(/index\.html$/,'');const canonical=new URL(base+route,origin).href;if(file!=='dist/404.html'&&$('link[rel=canonical]').attr('href')!==canonical)errors.push(`${file}: wrong canonical`);
 if(preview&&$('meta[name=robots]').attr('content')!=='noindex,nofollow')errors.push(`${file}: missing noindex`);if(!preview&&$('meta[name=robots]').length)errors.push(`${file}: production noindex`);
 $('a[href],img[src],video[src],video[poster],link[href],script[src]').each((_,el)=>{for(const attribute of ['href','src','poster']){const value=$(el).attr(attribute);if(file==='dist/404.html'&&$(el).attr('rel')==='canonical')continue;if(!value||/^(mailto:|tel:|data:)/.test(value))continue;let target;try{target=new URL(value,new URL(base+route,origin))}catch{errors.push(`${file}: invalid URL ${value}`);continue}if(target.origin!==origin)continue;if(value.startsWith(origin+'/')&&projectNames.includes(target.pathname.split('/')[1]))continue;
 if(!target.pathname.startsWith(base+'/')){errors.push(`${file}: link outside base ${value}`);continue}const relative=decodeURIComponent(target.pathname.slice(base.length));let targetFile=path.join('dist',relative);if(relative.endsWith('/'))targetFile=path.join(targetFile,'index.html');if(!fs.existsSync(targetFile)){errors.push(`${file}: missing local target ${value}`);continue}if(target.hash&&targetFile.endsWith('.html')&&docs.has(targetFile)&&!docs.get(targetFile)(`[id="${decodeURIComponent(target.hash.slice(1))}"]`).length)errors.push(`${file}: missing fragment ${value}`);
 }});
 $('img').each((_,el)=>{if(!$(el).attr('alt'))errors.push(`${file}: missing image alternative`)});if($('[src*="unist.info"],[src*="bluehost"]').length)errors.push(`${file}: external WordPress media`);
}
const bytes=bytesIn('dist');if(bytes>20_000_000)errors.push(`Homepage output exceeds 20 MB: ${bytes}`);if(errors.length)throw new Error(errors.join('\n'));console.log(`Built ${htmlFiles.length} pages; links, local media, canonical and index policy passed; ${bytes} bytes.`);
